owner: LuizKraisch
repo: flickmemo-status

sites:
  - name: Flickmemo API
    url: http://24.144.88.242/

status-website:
  logoUrl: https://raw.githubusercontent.com/LuizKraisch/flickmemo/main/assets/logos/flickmemo-logo-small.png
  name: Flickmemo
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "This is the Flickmemo's API current status."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
